export const environment = {
	production: true,
	isMockEnabled: false, // You have to switch this, when your real back-end is done
	authTokenKey: 'accessToken',
	// Old IP address 40.89.152.186
	// ------------------------ NAIMA SAHIH-----------------[Url back-end]
	reclamationUrl: 'http://marrakech.jamaati.ma:8080/gateway/Reclamation/Reclamations/Reclamation/',
	ppsourceUrl: 'http://marrakech.jamaati.ma:8080/gateway/Ppsource/PpSource/PPSource',
	pmsourceUrl: 'http://marrakech.jamaati.ma:8080/gateway/Pmsource/PmSource/PMSource',
	reservationUrl: 'http://marrakech.jamaati.ma:8080/gateway/Reservation/Reservations/Reservation/',
	bienReservationUrl: "http://marrakech.jamaati.ma:8080/gateway/Reservation/Reservations/BiensReservation/",
	espaceReservationUrl: "http://marrakech.jamaati.ma:8080/gateway/Reservation/Reservations/EspacesReservation/",
	bienUrl: 'http://marrakech.jamaati.ma:8080/gateway/Autorisation/Autorisations/Biens/',
	espaceUrl: 'http://marrakech.jamaati.ma:8080/gateway/Autorisation/Autorisations/EspaceReservation/',
	autorisationUrl: 'http://marrakech.jamaati.ma:8080/gateway/Autorisation/Autorisations/Autorisation/',
	marcheUrl: 'http://marrakech.jamaati.ma:8080/gateway/Marche/Marches',
	affaireConseilUrl: 'http://marrakech.jamaati.ma:8080/gateway/AffaireConseil/AffairesConseil/AffaireConseil/',
	
	personnelUrl: 'http://marrakech.jamaati.ma:8080/gateway/Personnel/Personnel',
	attestationUrl: 'http://marrakech.jamaati.ma:8080/gateway/Attestation/Attestation',
	notationUrl: 'http://marrakech.jamaati.ma:8080/gateway/Notation/Notation',
	permanenceUrl: 'http://marrakech.jamaati.ma:8080/gateway/Permanence/Permanence',
	presenceUrl: 'http://marrakech.jamaati.ma:8080/gateway/Presence/Presence',
	userUrl: 'http://marrakech.jamaati.ma:8080/gateway/Users/Users',
	organisationUrl: 'http://marrakech.jamaati.ma:8080/gateway/Organisation/Organisation',
	patrimoineUrl: 'http://marrakech.jamaati.ma:8080/gateway/PC/PatrimoineCommunal',
	immatriculationUrl: 'http://marrakech.jamaati.ma:8080/gateway/Immatriculation/Immatriculation',
	biencommunalUrl: 'http://marrakech.jamaati.ma:8080/gateway/BC/SuiviBienCommunal',
	projetUrl: 'http://marrakech.jamaati.ma:8080/gateway/Projet/Projet',

	API_BUREAU_ORDRE_URL: 'http://marrakech.jamaati.ma:8080/gateway/bureau-order/bureau-order',
	API_IMMOBILISATION_URL: 'http://marrakech.jamaati.ma:8080/gateway/immobilisation/immobilisation',
	API_INSERT_PUB_URL: 'http://marrakech.jamaati.ma:8080/gateway/insertion-publicitaire/insertion-publicitaire',
	API_ASSOCIATION_URL: 'http://marrakech.jamaati.ma:8080/gateway/association/association',
	API_SUBVENTION_URL: 'http://marrakech.jamaati.ma:8080/gateway/subvention/subvention',
	API_CONVENTION: 'http://marrakech.jamaati.ma:8080/gateway/convention/convention',
	API_PROJET_PARTENARIAT: 'http://marrakech.jamaati.ma:8080/gateway/projet-partenariat/projet-partenariat',
	API_ACTIVITE_URL: 'http://marrakech.jamaati.ma:8080/gateway/activite/activite',
	API_LOCAUX_URL: 'http://marrakech.jamaati.ma:8080/gateway/locaux/locaux',
	API_INTERVENTION_URL: 'http://marrakech.jamaati.ma:8080/gateway/intervention-rapide/intervention-rapide',
	API_PROJET_URBANISME_URL: 'http://marrakech.jamaati.ma:8080/gateway/projet-urbanisme/projet-urbanisme',
	API_ALFRESCO_URL: 'http://marrakech.jamaati.ma:8080/gateway/alfresco/alfresco',
	SERVER_URL:"http://marrakech.jamaati.ma:8080/gateway/",
	SERVER_URL_Stock:"http://marrakech.jamaati.ma:8080/gateway/gestionStock/",
	API_MARCHEGROS:"http://marrakech.jamaati.ma:8080/gateway/marche-gros/marche-gros/api/",
	API_ABATOIR:"http://marrakech.jamaati.ma:8080/gateway/service-abattoir/service-abattoir/api/",
	SERVER_PARC_AUTO:"http://marrakech.jamaati.ma:8080/gateway/gestionParc/",
	API_BMH_URL:"http://marrakech.jamaati.ma:8080/gateway/service-bmh/Bmh/",

};
